# To build: docker compose build
# To run: docker compose up
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - database

  auth-service:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - database

  database:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - '3306'

volumes:
  dbdata:
