# To build: docker compose build
# To run: docker compose up
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_HOST_URL=${HOST_URL}
    environment:
      - REACT_APP_HOST_URL=${HOST_URL}
    ports:
      - "3000:80"
    depends_on:
      - database

  auth-service:
    build:
      context: ./backend
      dockerfile: auth_service/Dockerfile
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - HOST_URL=${HOST_URL}
    ports:
      - "8000:8000"
    depends_on:
      - database

  audio-service:
    build:
      context: ./backend
      dockerfile: audio_service/Dockerfile
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - HOST_URL=${HOST_URL}
    ports:
      - "7500:8000"
    depends_on:
      - database

  meeting-service:
    build:
      context: ./backend
      dockerfile: meeting_service/Dockerfile
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - HOST_URL=${HOST_URL}
    ports:
      - "7000:7000"
    depends_on:
      - database

  database:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"