name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
        env:
          MYSQL_ROOT_PASSWORD: "test"
          MYSQL_DATABASE: "test"

      - name: docker compose build microservices and frontend 
        run: |
          docker-compose build
          
  deploy:
    runs-on: self-hosted

    steps:
      - name: Navigate to project directory
        run: |
          cd ~/Documents/THack_Mafia

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Shut down existing Docker containers
        run: |
          docker-compose down

      - name: Build and start Docker containers
        run: |
          docker-compose up -d


      

      



    